name: Daily Mirror to DumpstarrFire Repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dumpstarr Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      - name: Clean and Filter History
        run: |
          # Remove the folders/files from all branches and tags
          git filter-repo --path README.md --path .github/ --invert-paths --force

      - name: Push to DumpstarrFire
        env:
          DEST_URL: "https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/DumpstarrFire/Database.git"
        run: |
          git remote add destination "${DEST_URL}"
          git push destination --mirror --force
